services:
  - type: web
    name: flask-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.main:app"
    envVars:
      - key: FLASK_ENV
        value: production
